In [1]:
import numpy as np

In [3]:
from tempfile import TemporaryFile
outfile = TemporaryFile()

In [4]:
x = np.arange(10)
np.save(outfile, x)

In [5]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
_ = outfile.seek(0) # Only needed here to simulate closing & reopening file
np.load(outfile)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.save('test', x, allow_pickle=True, fix_imports=True)

In [14]:
np.load('../data/X_train.npy', mmap_mode=None, allow_pickle=False, fix_imports=True, encoding='ASCII')

array([[[[255],
         [255],
         [255],
         ...,
         [255],
         [255],
         [255]],

        [[255],
         [255],
         [255],
         ...,
         [255],
         [255],
         [255]],

        [[255],
         [255],
         [255],
         ...,
         [255],
         [255],
         [255]],

        ...,

        [[255],
         [255],
         [255],
         ...,
         [255],
         [255],
         [255]],

        [[255],
         [255],
         [255],
         ...,
         [255],
         [255],
         [255]],

        [[255],
         [255],
         [255],
         ...,
         [255],
         [255],
         [255]]],


       [[[255],
         [255],
         [255],
         ...,
         [255],
         [255],
         [255]],

        [[255],
         [255],
         [255],
         ...,
         [255],
         [255],
         [255]],

        [[255],
         [255],
         [255],
         ...,
         [255],
         [